# Titles -------------------------------------------
admin_title:
    pattern:  admin/title
    defaults: { _controller: AppPagePartsBundle:Title:index }

admin_title_new:
    pattern:  admin/title/new
    defaults: { _controller: AppPagePartsBundle:Title:new }

admin_title_create:
    pattern:  admin/title/create
    defaults: { _controller: AppPagePartsBundle:Title:create }

admin_title_show:
    pattern:  admin/title/{id}
    defaults: { _controller: AppPagePartsBundle:Title:show }

admin_title_edit:
    pattern:  admin/title/{id}/edit
    defaults: { _controller: AppPagePartsBundle:Title:edit }

admin_title_delete:
    pattern:  admin/title/delete/{id}
    defaults: { _controller: AppPagePartsBundle:Title:delete }

admin_title_update:
    pattern:  admin/title/update/{id}
    defaults: { _controller: AppPagePartsBundle:Title:update }

# Subtitles -------------------------------------------
admin_subtitle1:
    pattern:  admin/subtitle1
    defaults: { _controller: AppPagePartsBundle:Subtitle1:index }

admin_subtitle1_new:
    pattern:  admin/subtitle1/new
    defaults: { _controller: AppPagePartsBundle:Subtitle1:new }

admin_subtitle1_create:
    pattern:  admin/subtitle1/create
    defaults: { _controller: AppPagePartsBundle:Subtitle1:create }

admin_subtitle1_show:
    pattern:  admin/subtitle1/{id}
    defaults: { _controller: AppPagePartsBundle:Subtitle1:show }

admin_subtitle1_edit:
    pattern:  admin/subtitle1/{id}/edit
    defaults: { _controller: AppPagePartsBundle:Subtitle1:edit }

admin_subtitle1_delete:
    pattern:  admin/subtitle1/delete/{id}
    defaults: { _controller: AppPagePartsBundle:Subtitle1:delete }

admin_subtitle1_update:
    pattern:  admin/subtitle1/update/{id}
    defaults: { _controller: AppPagePartsBundle:Subtitle1:update }



admin_subtitle2:
    pattern:  admin/subtitle2
    defaults: { _controller: AppPagePartsBundle:Subtitle2:index }

admin_subtitle2_new:
    pattern:  admin/subtitle2/new
    defaults: { _controller: AppPagePartsBundle:Subtitle2:new }

admin_subtitle2_create:
    pattern:  admin/subtitle2/create
    defaults: { _controller: AppPagePartsBundle:Subtitle2:create }

admin_subtitle2_show:
    pattern:  admin/subtitle2/{id}
    defaults: { _controller: AppPagePartsBundle:Subtitle2:show }

admin_subtitle2_edit:
    pattern:  admin/subtitle2/{id}/edit
    defaults: { _controller: AppPagePartsBundle:Subtitle2:edit }

admin_subtitle2_delete:
    pattern:  admin/subtitle2/delete/{id}
    defaults: { _controller: AppPagePartsBundle:Subtitle2:delete }

admin_subtitle2_update:
    pattern:  admin/subtitle2/update/{id}
    defaults: { _controller: AppPagePartsBundle:Subtitle2:update }


admin_subtitle3:
    pattern:  admin/subtitle3
    defaults: { _controller: AppPagePartsBundle:Subtitle3:index }

admin_subtitle3_new:
    pattern:  admin/subtitle3/new
    defaults: { _controller: AppPagePartsBundle:Subtitle3:new }

admin_subtitle3_create:
    pattern:  admin/subtitle3/create
    defaults: { _controller: AppPagePartsBundle:Subtitle3:create }

admin_subtitle3_show:
    pattern:  admin/subtitle3/{id}
    defaults: { _controller: AppPagePartsBundle:Subtitle3:show }

admin_subtitle3_edit:
    pattern:  admin/subtitle3/{id}/edit
    defaults: { _controller: AppPagePartsBundle:Subtitle3:edit }

admin_subtitle3_delete:
    pattern:  admin/subtitle3/delete/{id}
    defaults: { _controller: AppPagePartsBundle:Subtitle3:delete }

admin_subtitle3_update:
    pattern:  admin/subtitle3/update/{id}
    defaults: { _controller: AppPagePartsBundle:Subtitle3:update }



# links -------------------------------------------
admin_link:
    pattern:  admin/link
    defaults: { _controller: AppPagePartsBundle:Link:index }

admin_link_new:
    pattern:  admin/link/new
    defaults: { _controller: AppPagePartsBundle:Link:new }

admin_link_create:
    pattern:  admin/link/create
    defaults: { _controller: AppPagePartsBundle:Link:create }

admin_link_show:
    pattern:  admin/link/{id}
    defaults: { _controller: AppPagePartsBundle:Link:show }

admin_link_edit:
    pattern:  admin/link/{id}/edit
    defaults: { _controller: AppPagePartsBundle:Link:edit }

admin_link_delete:
    pattern:  admin/link/delete/{id}
    defaults: { _controller: AppPagePartsBundle:Link:delete }

admin_link_update:
    pattern:  admin/link/update/{id}
    defaults: { _controller: AppPagePartsBundle:Link:update }


# links -------------------------------------------
admin_link:
    pattern:  admin/link
    defaults: { _controller: AppPagePartsBundle:Link:index }

admin_link_new:
    pattern:  admin/link/new
    defaults: { _controller: AppPagePartsBundle:Link:new }

admin_link_create:
    pattern:  admin/link/create
    defaults: { _controller: AppPagePartsBundle:Link:create }

admin_link_show:
    pattern:  admin/link/{id}
    defaults: { _controller: AppPagePartsBundle:Link:show }

admin_link_edit:
    pattern:  admin/link/{id}/edit
    defaults: { _controller: AppPagePartsBundle:Link:edit }

admin_link_delete:
    pattern:  admin/link/delete/{id}
    defaults: { _controller: AppPagePartsBundle:Link:delete }

admin_link_update:
    pattern:  admin/link/update/{id}
    defaults: { _controller: AppPagePartsBundle:Link:update }



# short text -------------------------------------------
admin_short:
    pattern:  admin/short
    defaults: { _controller: AppPagePartsBundle:Short:index }

admin_short_new:
    pattern:  admin/short/new
    defaults: { _controller: AppPagePartsBundle:Short:new }

admin_short_create:
    pattern:  admin/short/create
    defaults: { _controller: AppPagePartsBundle:Short:create }

admin_short_show:
    pattern:  admin/short/{id}
    defaults: { _controller: AppPagePartsBundle:Short:show }

admin_short_edit:
    pattern:  admin/short/{id}/edit
    defaults: { _controller: AppPagePartsBundle:Short:edit }

admin_short_delete:
    pattern:  admin/short/delete/{id}
    defaults: { _controller: AppPagePartsBundle:Short:delete }

admin_short_update:
    pattern:  admin/short/update/{id}
    defaults: { _controller: AppPagePartsBundle:Short:update }



# long text -------------------------------------------
admin_long:
    pattern:  admin/long
    defaults: { _controller: AppPagePartsBundle:Long:index }

admin_long_new:
    pattern:  admin/long/new
    defaults: { _controller: AppPagePartsBundle:Long:new }

admin_long_create:
    pattern:  admin/long/create
    defaults: { _controller: AppPagePartsBundle:Long:create }

admin_long_show:
    pattern:  admin/long/{id}
    defaults: { _controller: AppPagePartsBundle:Long:show }

admin_long_edit:
    pattern:  admin/long/{id}/edit
    defaults: { _controller: AppPagePartsBundle:Long:edit }

admin_long_delete:
    pattern:  admin/long/delete/{id}
    defaults: { _controller: AppPagePartsBundle:Long:delete }

admin_long_update:
    pattern:  admin/long/update/{id}
    defaults: { _controller: AppPagePartsBundle:Long:update }