<?php

namespace App\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainRepository extends EntityRepository
{
}
