# Index page "main" -------------------------------------------
admin_page_main:
    pattern:  admin/page/main
    defaults: { _controller: AppPageBundle:Main:index }

admin_page_main_new:
    pattern:  admin/page/main/new
    defaults: { _controller: AppPageBundle:Main:new }

admin_page_main_create:
    pattern:  admin/page/main/create
    defaults: { _controller: AppPageBundle:Main:create }

admin_page_main_show:
    pattern:  admin/page/main/{id}
    defaults: { _controller: AppPageBundle:Main:show }

admin_page_main_edit:
    pattern:  admin/page/main/{id}/edit
    defaults: { _controller: AppPageBundle:Main:edit }

admin_page_main_delete:
    pattern:  admin/page/main/delete/{id}
    defaults: { _controller: AppPageBundle:Main:delete }

admin_page_main_update:
    pattern:  admin/page/main/update/{id}
    defaults: { _controller: AppPageBundle:Main:update }


# Note entreprise 'company' -----------------------------------
admin_page_company:
    pattern:  admin/page/company
    defaults: { _controller: AppPageBundle:Company:index }

admin_page_company_new:
    pattern:  admin/page/company/new
    defaults: { _controller: AppPageBundle:Company:new }

admin_page_company_create:
    pattern:  admin/page/company/create
    defaults: { _controller: AppPageBundle:Company:create }

admin_page_company_show:
    pattern:  admin/page/company/{id}
    defaults: { _controller: AppPageBundle:Company:show }

admin_page_company_edit:
    pattern:  admin/page/company/{id}/edit
    defaults: { _controller: AppPageBundle:Company:edit }

admin_page_company_delete:
    pattern:  admin/page/company/delete/{id}
    defaults: { _controller: AppPageBundle:Company:delete }

admin_page_company_update:
    pattern:  admin/page/company/update/{id}
    defaults: { _controller: AppPageBundle:Company:update }



# Nos Services 'Services' -------------------------------------
admin_page_services:
    pattern:  admin/page/services
    defaults: { _controller: AppPageBundle:Services:index }

admin_page_services_new:
    pattern:  admin/page/services/new
    defaults: { _controller: AppPageBundle:Services:new }

admin_page_services_create:
    pattern:  admin/page/services/create
    defaults: { _controller: AppPageBundle:Services:create }

admin_page_services_show:
    pattern:  admin/page/services/{id}
    defaults: { _controller: AppPageBundle:Services:show }

admin_page_services_edit:
    pattern:  admin/page/services/{id}/edit
    defaults: { _controller: AppPageBundle:Services:edit }

admin_page_services_delete:
    pattern:  admin/page/services/delete/{id}
    defaults: { _controller: AppPageBundle:Services:delete }

admin_page_services_update:
    pattern:  admin/page/services/update/{id}
    defaults: { _controller: AppPageBundle:Services:update }



# Les autre pages ---------------------------------------------
admin_page_page:
    pattern:  admin/page/page
    defaults: { _controller: AppPageBundle:Page:index }

admin_page_page_new:
    pattern:  admin/page/page/new
    defaults: { _controller: AppPageBundle:Page:new }

admin_page_page_create:
    pattern:  admin/page/page/create
    defaults: { _controller: AppPageBundle:Page:create }

admin_page_page_show:
    pattern:  admin/page/page/{id}
    defaults: { _controller: AppPageBundle:Page:show }

admin_page_page_edit:
    pattern:  admin/page/page/{id}/edit
    defaults: { _controller: AppPageBundle:Page:edit }

admin_page_page_delete:
    pattern:  admin/page/page/delete/{id}
    defaults: { _controller: AppPageBundle:Page:delete }

admin_page_page_update:
    pattern:  admin/page/page/update/{id}
    defaults: { _controller: AppPageBundle:Page:update }