parameters:
#    app_page.example.class: App\PageBundle\Example

services:
#    app_page.example:
#        class: %app_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
