<?php

namespace App\SubsectionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Box6Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Box6Repository extends EntityRepository
{
}
