# boxes
admin_box1:
    pattern:  admin/box1
    defaults: { _controller: AppSubsectionBundle:Box1:index }

admin_box1_new:
    pattern:  admin/box1/new
    defaults: { _controller: AppSubsectionBundle:Box1:new }

admin_box1_create:
    pattern:  admin/box1/create
    defaults: { _controller: AppSubsectionBundle:Box1:create }

admin_box1_show:
    pattern:  admin/box1/{id}
    defaults: { _controller: AppSubsectionBundle:Box1:show }

admin_box1_edit:
    pattern:  admin/box1/{id}/edit
    defaults: { _controller: AppSubsectionBundle:Box1:edit }

admin_box1_delete:
    pattern:  admin/box1/delete/{id}
    defaults: { _controller: AppSubsectionBundle:Box1:delete }

admin_box1_update:
    pattern:  admin/box1/update/{id}
    defaults: { _controller: AppSubsectionBundle:Box1:update }


admin_box2:
    pattern:  admin/box2
    defaults: { _controller: AppSubsectionBundle:Box2:index }

admin_box2_new:
    pattern:  admin/box2/new
    defaults: { _controller: AppSubsectionBundle:Box2:new }

admin_box2_create:
    pattern:  admin/box2/create
    defaults: { _controller: AppSubsectionBundle:Box2:create }

admin_box2_show:
    pattern:  admin/box2/{id}
    defaults: { _controller: AppSubsectionBundle:Box2:show }

admin_box2_edit:
    pattern:  admin/box2/{id}/edit
    defaults: { _controller: AppSubsectionBundle:Box2:edit }

admin_box2_delete:
    pattern:  admin/box2/delete/{id}
    defaults: { _controller: AppSubsectionBundle:Box2:delete }

admin_box2_update:
    pattern:  admin/box2/update/{id}
    defaults: { _controller: AppSubsectionBundle:Box2:update }



admin_box3:
    pattern:  admin/box3
    defaults: { _controller: AppSubsectionBundle:Box3:index }

admin_box3_new:
    pattern:  admin/box3/new
    defaults: { _controller: AppSubsectionBundle:Box3:new }

admin_box3_create:
    pattern:  admin/box3/create
    defaults: { _controller: AppSubsectionBundle:Box3:create }

admin_box3_show:
    pattern:  admin/box3/{id}
    defaults: { _controller: AppSubsectionBundle:Box3:show }

admin_box3_edit:
    pattern:  admin/box3/{id}/edit
    defaults: { _controller: AppSubsectionBundle:Box3:edit }

admin_box3_delete:
    pattern:  admin/box3/delete/{id}
    defaults: { _controller: AppSubsectionBundle:Box3:delete }

admin_box3_update:
    pattern:  admin/box3/update/{id}
    defaults: { _controller: AppSubsectionBundle:Box3:update }




admin_box4:
    pattern:  admin/box4
    defaults: { _controller: AppSubsectionBundle:Box4:index }

admin_box4_new:
    pattern:  admin/box4/new
    defaults: { _controller: AppSubsectionBundle:Box4:new }

admin_box4_create:
    pattern:  admin/box4/create
    defaults: { _controller: AppSubsectionBundle:Box4:create }

admin_box4_show:
    pattern:  admin/box4/{id}
    defaults: { _controller: AppSubsectionBundle:Box4:show }

admin_box4_edit:
    pattern:  admin/box4/{id}/edit
    defaults: { _controller: AppSubsectionBundle:Box4:edit }

admin_box4_delete:
    pattern:  admin/box4/delete/{id}
    defaults: { _controller: AppSubsectionBundle:Box4:delete }

admin_box4_update:
    pattern:  admin/box4/update/{id}
    defaults: { _controller: AppSubsectionBundle:Box4:update }




admin_box5:
    pattern:  admin/box5
    defaults: { _controller: AppSubsectionBundle:Box5:index }

admin_box5_new:
    pattern:  admin/box5/new
    defaults: { _controller: AppSubsectionBundle:Box5:new }

admin_box5_create:
    pattern:  admin/box5/create
    defaults: { _controller: AppSubsectionBundle:Box5:create }

admin_box5_show:
    pattern:  admin/box5/{id}
    defaults: { _controller: AppSubsectionBundle:Box5:show }

admin_box5_edit:
    pattern:  admin/box5/{id}/edit
    defaults: { _controller: AppSubsectionBundle:Box5:edit }

admin_box5_delete:
    pattern:  admin/box5/delete/{id}
    defaults: { _controller: AppSubsectionBundle:Box5:delete }

admin_box5_update:
    pattern:  admin/box5/update/{id}
    defaults: { _controller: AppSubsectionBundle:Box5:update }
