app_page:
    resource: "@AppPageBundle/Resources/config/routing.yml"
    prefix:   /

app_subsection:
    resource: "@AppSubsectionBundle/Resources/config/routing.yml"
    prefix:   /

app_page_parts:
    resource: "@AppPagePartsBundle/Resources/config/routing.yml"
    prefix:   /

app_contact:
    resource: "@AppContactBundle/Resources/config/routing.yml"
    prefix:   /

app_upload:
    resource: "@AppUploadBundle/Resources/config/routing.yml"
    prefix:   /

app_carousel:
    resource: "@AppCarouselBundle/Resources/config/routing.yml"
    prefix:   /

app_menu:
    resource: "@AppMenuBundle/Resources/config/routing.yml"
    prefix:   /

app_app:
    resource: "@AppAppBundle/Resources/config/routing.yml"
    prefix:   /

admin_admin:
    resource: "@AdminAdminBundle/Resources/config/routing.yml"
    prefix:   /