app_menu:
    resource: "@AppMenuBundle/Resources/config/routing.yml"
    prefix:   /

admin_menu:
    resource: "@AdminMenuBundle/Resources/config/routing.yml"
    prefix:   /

app_app:
    resource: "@AppAppBundle/Resources/config/routing.yml"
    prefix:   /

admin_admin:
    resource: "@AdminAdminBundle/Resources/config/routing.yml"
    prefix:   /