app_app_homepage:
    pattern:  /
    defaults: { _controller: AppAppBundle:App:index }

app_app_company:
    pattern:  /company
    defaults: { _controller: AppAppBundle:App:company }

app_app_services:
    pattern:  /services
    defaults: { _controller: AppAppBundle:App:services }

app_app_sitemap:
    pattern:  /sitemap
    defaults: { _controller: AppAppBundle:Sitemaps:sitemap }

app_app_page:
    pattern:  /{slug}
    defaults: { _controller: AppAppBundle:App:page }