parameters:
#    admin_menu.example.class: Admin\MenuBundle\Example

services:
#    admin_menu.example:
#        class: %admin_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
