<?php

namespace App\PagePartsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortRepository extends EntityRepository
{
}
