<?php

namespace App\PagePartsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Subtitle3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Subtitle3Repository extends EntityRepository
{
}
