parameters:
#    app_contact.example.class: App\ContactBundle\Example

services:
#    app_contact.example:
#        class: %app_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
